HOST: http://payb.in/v1

--- Fire API v1 ---
---
Now editing in Eclipse! All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
Sample Resources
The following is a section of resources related to the person sample
--
Retrieve a sample person. (comment block again in Markdown)
POST /request
< 200
< Content-Type: application/json
{"user": {"email":"owen.obyrne@gmail.com"},"amount":2000,"currency":"EUR","message": "U17's first term fees"}

Save new products in your shopping cart
POST /person
> Content-Type: application/x-www-form-urlencoded
firstName=Owen&lastName=O+Byrne&email=owen.obyrne@iol.ie
< 201
< Content-Type: application/json
{"email":"owen.obyrne@iol.ie","firstName":"Owen","id":"1","lastName":"O Byrne"}

-- Payment Resources --
This resource allows you to submit payment information to process your *shopping cart* items
POST /payment
{ "cc": "12345678900", "cvc": "123", "expiry": "0112" }
< 200
{ "receipt": "/payment/receipt/1" }